apiVersion: v1
kind: Service
metadata:
  name: python-helloworld
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: python-helloworld
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: web